### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xennn** [O365Squad/O365-Squatting#3]
Traceback (most recent call last):
  File "o365squatting.py", line 3, in <module>
    import pycef
  File "/usr/local/lib/python2.7/dist-packages/pycef/__init__.py", line 43
    logger.warning(f'Blank field(s) in CEF header. Is it valid CEF format?')
                                                                          ^
SyntaxError: invalid syntax

**Comment by O365Squad** [comment]
Hi xennn,

this was already clarified on #1 

Now you have 2 folderes in this project: python2 and python3. For python2 please follow the steps described in the README file.

Thank you.
