### ISSUE TITLE
domains with .com.XX extension

### ISSUE THREAD

**Issue by jman-foobar** [O365Squad/O365-Squatting#4]
Domains with a .com.XX or .gov.XX throws an error...
Reason is def __domain_tld(self, domain) function only handles a length of 2 
A quick fix is to add to end of function
if len(domain) == 3:
      return domain[0], domain[1]+'.'+domain[2]

**Comment by O365Squad** [comment]
Hi jman-foobar,

thank you for both catching the issue and include a proposal to fix it.
At first we were not considering to use second level domains to check on O365, but we will add this feature in our next version.

Best Regards.
